# [START swagger]
swagger: "2.0"
info:
  description: "PII Service to manage and retrieve PII data"
  title: "PII Service"
  version: "1.0.0"
host: "pii-service.appspot.com"
# [END swagger]
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  - "https"
paths:
  "/pii/{id}":
    get:
      description: "Retrieve PII information."
      operationId: "pii-get"
      produces:
        - "application/json"
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "PII Data"
          schema:
            $ref: "#/definitions/piiData"
        400:
          description: Bad request. User ID must be an integer and larger than 0.
        401:
          description: Authorization information is missing or invalid.
        404:
          description: A user with the specified ID was not found.
        503:
          description: Unexpected error.
      security:
        - api_key: []
  "/pii":
    post:
      description: "Create PII information."
      operationId: "pii-create"
      produces:
        - "application/json"
      responses:
        200:
          description: "PII Created"
          schema:
            $ref: "#/definitions/resultMessage"
        400:
          description: Bad request - incorrect JSON.
        401:
          description: Authorization information is missing or invalid.
        503:
          description: Unexpected error.
      parameters:
        -
          description: "PII Data"
          in: body
          name: message
          required: true
          schema:
            $ref: "#/definitions/piiData"
      security:
        - api_key: []
definitions:
  resultMessage:
    type: "object"
    properties:
      message:
        type: "string"
      code:
        type: "integer"
  piiData:
    type: "object"
    properties:
      name:
        type: "string"
      phone:
        type: "string"
      email:
        type: "string"
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
